// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NgeOK6D9Z40dVXrZpDWyXuHPip6HqDM',
    appId: '1:489245215212:web:74d1ebdf380979e72dd8c9',
    messagingSenderId: '489245215212',
    projectId: 'fluxen-f8279',
    authDomain: 'fluxen-f8279.firebaseapp.com',
    storageBucket: 'fluxen-f8279.firebasestorage.app',
    measurementId: 'G-2Q3T6V3GB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpPSnpvNs908R2GMkycEnixzAFPglM7E',
    appId: '1:659756040536:android:c13a20d09136c23d8ca52d',
    messagingSenderId: '659756040536',
    projectId: 'fluxen-ca58f',
    storageBucket: 'fluxen-ca58f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF7UlHwN6CGR7BeHpqjfLIt6dtuPlcHLw',
    appId: '1:489245215212:ios:ee2853535cc3e89c2dd8c9',
    messagingSenderId: '489245215212',
    projectId: 'fluxen-f8279',
    storageBucket: 'fluxen-f8279.firebasestorage.app',
    iosBundleId: 'com.example.fluxen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF7UlHwN6CGR7BeHpqjfLIt6dtuPlcHLw',
    appId: '1:489245215212:ios:ee2853535cc3e89c2dd8c9',
    messagingSenderId: '489245215212',
    projectId: 'fluxen-f8279',
    storageBucket: 'fluxen-f8279.firebasestorage.app',
    iosBundleId: 'com.example.fluxen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9NgeOK6D9Z40dVXrZpDWyXuHPip6HqDM',
    appId: '1:489245215212:web:5c109a628341abf62dd8c9',
    messagingSenderId: '489245215212',
    projectId: 'fluxen-f8279',
    authDomain: 'fluxen-f8279.firebaseapp.com',
    storageBucket: 'fluxen-f8279.firebasestorage.app',
    measurementId: 'G-P6KN9BH9QL',
  );

  
}